GSGameStats =  
{
	Players = 6,
	WinBy = "",
	Scenario = "6p_Eight-tide_river",
	player_0 =  
	{
		PRace = "sisters_race",
		PHuman = 0,
		PFnlState = 1,
		PTeam = 0,
		PName = "Computer 3",
		PTtlSc = 137,
	},
	player_1 =  
	{
		PRace = "eldar_race",
		PHuman = 0,
		PFnlState = 1,
		PTeam = 0,
		PName = "Computer 5",
		PTtlSc = 197,
	},
	Duration = 45,
	player_4 =  
	{
		PRace = "ork_race",
		PHuman = 1,
		PFnlState = 3,
		PTeam = 1,
		PName = "Oshava",
		PTtlSc = 16,
	},
	player_2 =  
	{
		PRace = "chaos_marine_race",
		PHuman = 0,
		PFnlState = 1,
		PTeam = 0,
		PName = "Computer 4",
		PTtlSc = 167,
	},
	Teams = 2,
	player_3 =  
	{
		PRace = "ork_race",
		PHuman = 0,
		PFnlState = 1,
		PTeam = 1,
		PName = "Computer 1",
		PTtlSc = 212,
	},
	player_5 =  
	{
		PRace = "eldar_race",
		PHuman = 0,
		PFnlState = 1,
		PTeam = 1,
		PName = "Computer 2",
		PTtlSc = 197,
	},
}
